apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: The backstage sub-department
spec:
  type: sub-department
  parent: infrastructure
  children: [team-a, team-b]
