apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
spec:
  type: organization
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  type: github
  targets:
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/infrastructure-group.yaml
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/boxoffice-group.yaml
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/backstage-group.yaml
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/team-a-group.yaml
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/team-b-group.yaml
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/team-c-group.yaml
    - https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/team-d-group.yaml
