apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A
spec:
  type: team
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: breanna.davison
spec:
  profile:
    displayName: Breanna Davison
    email: breanna-davison@example.com
    picture: https://example.com/staff/breanna.jpeg
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://example.com/staff/janelle.jpeg
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning
spec:
  profile:
    displayName: Nigel Manning
    email: nigel-manning@example.com
    picture: https://example.com/staff/nigel.jpeg
  memberOf: [team-a]
